### ISSUE TITLE
「基于深度学习的自然语言处理」首期课程入学挑战

### ISSUE THREAD

**Issue by CrickeySong** [OpenMindClub/DeepLearningStartUp#1]
欢迎你报名内测开智学堂「基于深度学习的自然语言处理」课程！

参加这门课程需有一定基础，如果你想顺利参与这次内测，请在 2 月 24 日 11:42 前完成以下入学挑战哦：

## 挑战说明

1. 完成[《Learn Python the Hard Way》](http://learnpythonthehardway.org/book) 前 42 个小练习，如果精力不足，那至少完成前 17 个哦。据统计一般 20 ~ 30mins 就能完成一个小练习，相信你也可以~
2. 统计这篇 [文章](https://github.com/OpenMindClub/DeepLearningStartUp/blob/master/happiness_seg.txt) 中，出现频率最高的前 10 个「二元词组」，并输出它们的频率。「二元词组」即文章中所有接连出现的两个词，如「今天 天气 不错」有「今天 天气」，「天气 不错」两个「二元词组」。
3. 将上述成果同步到个人 GitHub 公开仓库，仓库名自定。建议你使用 Git 命令同步。

## 提交方式

- 在本仓库中新建一个 Issue 
	- Issue title 为 `[你的名号]完成 DL101 入学挑战啦` ，例如： 云嫱完成 DL101 入学挑战啦
	-  Issue 正文包括两部分
		- 含有你上述挑战成果的 GitHub 仓库地址
		- 140 字以上感想，比如希望大家关注/讨论的技术点，或是自个儿的体验点
- 提交截止时间：2017 年 2 月 24 日（周五） 11:42

## 其它 

1. 如果你适合参加本期课程，将在 2 月 24 日 24:00 前收到邮件通知正式进入课程学习；如果没能在截止时间前完成，将在 2017 年 3 月 4 日 24:00 前收到沿原支付渠道退还的全额学费。
2. 对挑战细节有什么不清楚，欢迎在这个仓库发 Issue 提出；挑战过程中遇到困难，欢迎在本仓库发 Issue ，和其他学友交流探讨。也期待你多多在 Issues 和其他学友互动：D
3. 提交任务后，如果你还有时间，可根据课程参考书提前学习：[Neural Networks and Deep Learning（英文版](http://neuralnetworksanddeeplearning.com/index.html)/[中文版）](https://tigerneil.gitbooks.io/neural-networks-and-deep-learning-zh/content/)

期待你的挑战成果~

**Comment by newjueqi** [comment]
请问提交结果到自己的github时，只需要最终结果吗？所使用的python代码需要提交吗？

**Comment by CrickeySong** [comment]
@newjueqi python 代码也需要提交哦，如果同时附上你的笔记和心得就更好啦~

**Comment by ZhaoXiaopeng1979** [comment]
请教呀，咱的课程是用Python2.x还是Python3.x ?

**Comment by zj05409** [comment]
test

**Comment by thycoder** [comment]
test

**Comment by hscspring** [comment]
@ZhaoXiaopeng1979 都可以。示例代码用的 Python2

**Comment by CrickeySong** [comment]
本次课程已正式开课，打上 achivement 标签的同学都收到欢迎邮件了吧?若没有的话请尽快联系一休（aiopenmind001）哦。其他想要参加课程的同学可以预约下一期哦：http://openmind.mikecrm.com/7H2vih
