### ISSUE TITLE
[00]完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by kidult00** [OpenMindClub/DeepLearningStartUp#10]
代码地址：https://github.com/kidult00/2017.OM.DL

感想：

虽然上过 Python 一期，但是久不写代码又生疏了好多。参考了[尉阮杰](https://github.com/cutebomb/DeepLearningStartUp) 和 [Corey](https://github.com/chuanwj/DeepLearningStartUp) 两位同学的代码完成了作业。过程中遇到的问题：

1. 开始以为要用 Jieba 分词工具，看了一下文档，开始做以后才发现词已经分好了
2. 文件读写和编码问题，在 terminal 中调试时无法显示中文字符，后来用 codecs 模块解决
3. 对二元词组的理解问题，一开始以为是单个单词的词频统计，后来才反应过来应该是两个邻近词组
4. 重新复习了一下数组和字典，之前忘得差不多了囧
5. 字典排序卡了很久，参考同学们的代码以及学习 [Lambda 表达式的用法](https://www.zhihu.com/question/20125256) 后解决

作业难度比想象中要大。自己的编程和统计基础都不好，最近工作又特别忙，希望在课程中多跟同学们交流，能坚持下来。

**Comment by sunoonlee** [comment]
粉丝前排留名。仰慕很久了! 能够同班学习，好开心 😄

**Comment by kidult00** [comment]
@sunoonlee  啊呀我是编程小白，请大家多多关照！
