### ISSUE TITLE
[曾健生]完成 DL101 入学挑战啦 

### ISSUE THREAD

**Issue by newjueqi** [OpenMindClub/DeepLearningStartUp#11]
1.代码地址：

https://github.com/newjueqi/DeepLearningStartUp

输出结果：

[["这种情况", 77], ["没有什么", 70], ["这个问题", 57], ["因为他们", 55], ["如果我们", 50], ["所有这些", 47], ["这种观点", 46], ["这个世界", 40], ["他们自己", 38], ["我们可以", 37]]

2. 感想

现在的网络小说和公众号的心灵鸡汤都是套路，精品太少，感觉是换了人名，换了地点和背景又是新的。

既然文章已经高度雷同了，为啥不能使用人工智能来生成，就算是生成的作品质量比起写手写的差又有什么关系，看网络小说，更多是看寂寞。

当某些领域的文学创作变成了一种高度雷同的堆砌文字的体力活，就不可避免地被人工智能所替代（例如安替老师所提到地使用人工智能生成新闻稿），只有真正能创作真正优秀作品的作者才能存活下来。

**Comment by sunoonlee** [comment]
哇，出过书的大牛，膜拜！
