### ISSUE TITLE
zero 完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by junjielizero** [OpenMindClub/DeepLearningStartUp#15]
## Task 想法

- Task1：很早就做过前 42 道题练习，稍后再放
- Task2：[代码与结果](https://github.com/junjielizero/2017.OM.DL/blob/master/script/openmind-task.ipynb)

### 预处理

源文件有较多以下问题，故最终输出结果与其他学员可能不一致

- 源文件除了有很多空格外，还有很多回车行，部分制表符
- 全角与半角字符混合
- 前九章存在重复

感觉可能还有其他问题。。。

### 结果处理

- 基于数据分析考虑，使用的工具是 ``Jupyter Notebook`` 与 ``Python 3.5.2`` ，不知道之后的课程使用工具要求是哪样

- 「二元词组」定义，我默认是每个词长度大于 1 ，词组不包含数字、符号与非法字符，但不知实际要求是怎样

## 课程想法与疑问

- 「二元词组」在中文 NLP 技术中承担的角色有多大
- 现有 NLP 主要流派分析有哪些，感觉目前都以英文文本为主，实际上适用于中文的有哪些呢？

**Comment by txytju** [comment]
课程中使用`python2`和`python3`都可以，童老师的示例代码使用了`python2`，不过影响不大哈
