### ISSUE TITLE
[尉阮杰]完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by cutebomb** [OpenMindClub/DeepLearningStartUp#2]
代码地址：
https://github.com/cutebomb/DeepLearningStartUp

感想：
本人对NLP这个领域挺感兴趣的，开智学堂的课程的设计实践性应该挺好的，最后是要实现一个问答系统呢。再有一点小小的希望就是可以提供一下整个NLP领域的survey，可以让大家以后有什么问题不明白，可以把课程老师教的东西拿出来当做寻宝图来看一看，要找什么东西的设计或实践会就会比较有方向。另外呢，自然语言处理方向上，应用Deep Learning的方法，目前还有哪些问题点，是暂时还存有问题的，还有未解决的问题老师也可以介绍介绍，说不定学堂里未来就出现几个学术大牛能把这些问题解决一部分。特别是关于中文NLP的问题，应该是有一些特别的地方的，国外的研究机构不一定花大力气关注，这些地方可能会是国内深度学习技术的突破点呢：）

**Comment by ouyangzhiping** [comment]
1. 整个 NLP 领域的 survey

很赞，也许同学们可以齐心协力，来一份地图。可以仿照这种形式，将常见的 Python 库整理出来：

[Full Stack Python](https://www.fullstackpython.com/)

2. 自然语言处理方向上，应用 Deep Learning 的方法，目前还有哪些问题点，是暂时还存有问题的，还有未解决的问题

一些已有的资源，大家也可以参考：

英文版：[keon/awesome-nlp: A curated list of resources dedicated to Natural Language Processing (NLP)](https://github.com/keon/awesome-nlp)

中文版： [JustFollowUs/Natural-Language-Processing](https://github.com/JustFollowUs/Natural-Language-Processing)

**Comment by Jhangsy** [comment]
可以把得到的结果和大家分享一下么？ 👍

**Comment by cutebomb** [comment]
又看了一遍题，如果二元词组理解为两个二字词组的话结果为：('这种 情况', 77), ('没有 什么', 70), ('这个 问题', 56), ('因为 他们', 54), ('如果 我们', 47), ('这种 观点', 46), ('所有 这些', 44), ('这个 世界', 40), ('他们 自己', 38), ('我们 可以', 37)
如果大于1个字就能算词的话结果为：('的 人', 921), ('他 的', 503), ('自己 的', 479), ('上 的', 355), ('他们 的', 334), ('人 的', 293), ('的 时候', 261), ('就 会', 225), ('的 东西', 207), ('都 是', 206)
相应代码就是len ==2 还是len >=1 的区别
