### ISSUE TITLE
于耀程完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by MagicCheng** [OpenMindClub/DeepLearningStartUp#24]
- [代码地址](https://github.com/MagicCheng/DeeplearningStartup/blob/master/dl_chap0.py)
- Learn the Python Hard Way 还在进行中。因为会的有限，用了一种比较笨的办法来实现目标，做完发现跟小伙伴们的有出入。做任务的过程遇到了两个问题。一个是在我代码里标记的，在第一步做词典的时候第一次用的代码运行出来只针对文档最后一段，疑惑中。

```Python
 with open('happiness_seg.txt','r') as wordsfile:
     for words in wordsfile:
        word = words.split(' ')
```

第二是，我在考虑如果在处理文档之前就把标点符号去掉是否会出现误差。比如：
>  转移 自己 思考 目标 的 做法 是 由于 对于 鬼怪 幽灵 的 恐惧 引起 的 ， 人 由此 转移 了 自己 注视 的 目光 。

如果事先把逗号去掉，那么“的 人”就成了二元词组了。不知道隔了一个逗号算不算二元词组。我的代码没有把这样的算在内（只是考虑到了，但代码是否实现了没有自信），没有想出更优雅的姿势解决，抛砖引玉，欢迎大家多来讨论。
- 我是零基础在开智py103学的Python。慧根不足，但日拱一卒，慢慢也会写一点点代码。看见有小伙伴在发issue求助，自己水平有限，帮不上太多，在这分享下做任务的心路历程。看到这个任务首先要明确目标，是统计二元词组。那么先定义好什么是二元词组。接着，文本如何去改造成词典，又如何进一步做成二元词组。再者，如何计数。每一步都有小细节，比如标点符号的去除。我先在心里想象出流程，然后再一点点用代码实现。如果说基础再薄一点，比如，不知道词典为何物（我最开始学就不知道），那么可以先看看小伙伴的代码，对照自己会的，看看哪些节点不懂，然后google一下。看上几个人的代码（最好是思路不通的），把每个不会的节点碎片化，谷歌出来消化掉（其实就是卡片大法）。最后抛开别人的代码，把自己内化的方法拼凑起来，来实现自己的想法，做出来的可能跟之前看的都不同。LTPHW到20多节就有词典的概念了。用这之前学过的能把除了计数意外的做出来。话说计数我也是看别人分享的[链接](http://python3-cookbook.readthedocs.io/zh_CN/latest/c01/p12_determine_most_freqently_items_in_seq.html)才会的。
明天继续预习。不知我这样情况的能否通过初选。

**Comment by Jhangsy** [comment]
> 在第一步做词典的时候第一次用的代码运行出来只针对文档最后一段，疑惑中。

因为对于 ``` for x in inputfile:``` 是在文件中以**行**为单位循环。所以你的代码最后只会保留最后一次运行的结果。

> 不知道隔了一个逗号算不算二元词组

可以算也可以不算。

给大家的建议很好，这样一点一点的分解任务逐个完成确实是行之有效的方法~~
