### ISSUE TITLE
[13space]完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by 13space** [OpenMindClub/DeepLearningStartUp#25]
## 作业
一、完成《Learn Python the Hard Way》 前 42 个小练习，如果精力不足，那至少完成前 17 个哦。据统计一般 20 ~ 30mins 就能完成一个小练习，相信你也可以~

[ex1-17：](https://github.com/13space/NLP/blob/master/0w/ex1-17.ipynb)

二、
统计这篇 文章 中，出现频率最高的前 10 个「二元词组」，并输出它们的频率。「二元词组」即文章中所有接连出现的两个词，如「今天 天气 不错」有「今天 天气」，「天气 不错」两个「二元词组」。

[练习结果](https://github.com/13space/NLP/blob/master/0w/work0w.ipynb)

## 感想

虽然学过别的语言，但自己的python 基础还是太差，代码质量也惨不忍睹，简直是硬扛的感觉。。
需要多学多练，要不然效率完全上不去
但总之最小行动先把作业交了。我主要还是兴趣派，后面慢慢优化吧。。

**Comment by Jhangsy** [comment]
建议可以试试不用 NLTK.bigrams 来构建二元次组。
