### ISSUE TITLE
sunoonlee 完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by sunoonlee** [OpenMindClub/DeepLearningStartUp#26]
仓库地址：[sunoonlee/OMDL101pre](https://github.com/sunoonlee/OMDL101pre)

感想：
- 感谢开智 py102 的开智功效，从此不甘被乏味的旧工作束缚，想做点有趣的事情。现为准离职状态，方向探索期。
- 对深度学习毫无所知，大学那点工科数学也早忘完了。原想先自己预习一两个月，又不愿错过这期，所以就赶鸭子上架了
- 看到好几个熟悉的 ID，包括 Py102/3 的 教练、同学，开智部落学友等，真是无处不相逢。
- 不用说，这里一定是藏龙卧虎，努力向各位优秀同学看齐！

**Comment by Jhangsy** [comment]
建议可以试试不用 NLTK.bigrams 来构建二元次组。
