### ISSUE TITLE
入学挑战思路和问题

### ISSUE THREAD

**Issue by gunuo** [OpenMindClub/DeepLearningStartUp#28]
我还在下载软件中，但在看入学挑战时，有一个隐藏在task里的重大问题，我看前面的同学都没发现。
1）我看了一下原文件，虽然有空格，但是词语区分的并不是按照完全按照自然语言区分的。像下面一句话：“我见 过 的 一张 张 脸孔 ， 斑斑 懦弱 ， 点点 愁怨 。”至少我会按照，“我 见过 的 一张张”来区分。以此来推断，还是要先合并，而后用jieba分词来做预处理。
2）仔细来看，这个原文件中有3个部分。第一部分《幸福之路》有章节重复的现象。大概是前面2-9章有重复，它的分章节技巧可以使用**幸福之路**来进行索引，切片。第二部分是《悠闲颂》则不然，每一章的标题不同。而章节和章节之前区别，有的是用大写中文序词，有的是阿拉伯数字。这部分则不能使用特定的词语来索引。第三部分又是幸福之路。但和第一部分的内容完全不同。也有“幸福之路”做索引。这就变成了很复杂的任务。我的想法是首先用“幸福之路”索引，将文章切片。然后还需要手工将重复的部分替换。但如何依靠机器来替换重复的部分，还没有想好。

我还没有学会怎么整程序，思路我是这样想的。
思路是用python3，而不用python处理中文字符，因为python2要decoding然后encoding。要用nltk软件包。需要**先用程序把重复的段落消除**之后，再进行后续操作。
1、使用jieba程序分词。然后用string指令把前后两个词连接在一起。
这样，如果有逗号，就会出现“xx，”这样的形式。这自然克服了前后两句连接而成的缺陷。将前后两个词连接在一起之后，使用判断语句，看这个word是不是4个字。
2、但这也可能出现1+3或者3+1的情形。使用方法是在word4个字的集合中，再次使用jieba分词，看前后是不是2+2的形式。如此，之后，集合就干净了。这时候再来统计频数即可。

**Comment by newjueqi** [comment]
对于第一点，不需要合并，jieba分词会自动处理空格

**Comment by gunuo** [comment]
第二部分怎么办呢？我查了一个语句，是find和rfind来定义前后标签。那就是用“之路“做前面，“幸福“做后面，但是这只能是用raw.find来定义这个篇章里的一段一段。还是没办法把它delete掉啊
