### ISSUE TITLE
[fatfox2016]完成 DL101 入学挑战啦 

### ISSUE THREAD

**Issue by fatfox2016** [OpenMindClub/DeepLearningStartUp#3]
挑战成果: [GitHub 仓库地址](https://github.com/fatfox2016/LearnPythonTheHardWay)

感想:

从加入开智学习python起，就在不停的刷新认知。首先是自信心，作为十几年学校学习中的loser，对学习毫无信心可言。现在步入中年，记忆力更是剧烈下降。其次是元认知，16年以前我根本不知道这个概念，最近半年“认知科学”“设计模式”“元知识”等等概念的刷新，给我开了一扇窗。最后就是有耐心的执行，具体到python学习中，就是立刻写代码。
虽然目前我的数学能力只有初中生水平，编程能力只有python入门级，但是我相信只要有信心、耐心、恒心、细心，对Deep Learning的学习，我看到了希望。多说无用，先啃两口统计学、概率论去了。

**Comment by txytju** [comment]
课程中会用到一些基本的高数知识，不过不用担心，童牧老师的讲解非常细致~
