### ISSUE TITLE
yuanyifly完成DL101 入学挑战啦

### ISSUE THREAD

**Issue by yuanyifly** [OpenMindClub/DeepLearningStartUp#31]
已经重新上传了作业，地址是：https://github.com/yuanyifly/DeepLearning
结果：
的 人 923
他 的 503
自己 的 479
上 的 355
他们 的 335
人 的 293
的 时候 261
就 会 225
的 东西 207
都 是 206

感想：
　　之前搞错了题目意思，所以又重新写了一次，非常惭愧！本人目前是个菜鸟，接触Python 才半个月，这个作业的完成就是个不断试错的过程，完成的代码不精简也不优美，感觉自己学得真是太浅了……但是我对自己的有信心，对这门课程充满兴趣，尤其是有这么多优秀的同学在，也能鞭策自己不能松懈。
　　另外今早似乎是网络问题，怎么都进不来Github，所以上传地晚了点，不好意思！

**Comment by Jhangsy** [comment]
**二元词组** 是指连续的两词语，抓紧时间再修改一下吧~

**Comment by yuanyifly** [comment]
好的，请问是直接修改就好还是需要重新提交一次？谢谢！-------- 原始邮件 --------主题：Re: [OpenMindClub/DeepLearningStartUp] yuanyifly完成DL101 入学挑战啦 (#31)发件人：Jhang 收件人：OpenMindClub/DeepLearningStartUp 抄送：YuanYi ,Assign 二元词组 是指连续的两词语，抓紧时间再修改一下吧~

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenMindClub/DeepLearningStartUp","title":"OpenMindClub/DeepLearningStartUp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenMindClub/DeepLearningStartUp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Jhangsy in #31: **二元词组** 是指连续的两词语，抓紧时间再修改一下吧~"}],"action":{"name":"View Issue","url":"https://github.com/OpenMindClub/DeepLearningStartUp/issues/31#issuecomment-281994345"}}}

**Comment by Jhangsy** [comment]
直接修改就好 :)

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
