### ISSUE TITLE
[CarolLei]完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by CarolLei** [OpenMindClub/DeepLearningStartUp#38]
### [代码地址](https://github.com/CarolLei/MachineLearning)
注: Learn Python The Hard Way已经完整的敲过了前25个练习，就不在这里上传代码了。因为平时编程的实践很少，所以对语法还不够熟悉，编程的思路也锻炼的少，后面的17个练习会在开课前尽快再练习一遍。

### [ version_1](https://github.com/CarolLei/MachineLearning/blob/master/exercice0_v1.py)
a) 读取下载下来的文件data.txt
b) 用split进行切割, 将字符串变为列表，其中含有单独的标点和空字符
c) 用len读取显示为“\x”类的中文字符，发现两个汉字的长度为6，于是确立if条件
d) 拼接所有符合长度条件的词组，变成二元词组，依次放入一个空字典中
e) 用sort方法对value进行降序排列，print出前10个value最大的key

用version_1的结果对照了其它已提交作业的同学们的答案，发现我们在统计结果上有微小的差异。我输出的结果是：
#我的输出结果
#这种情况 : 77
#没有什么 : 70
#这个问题 : 56
#因为他们 : 54
#如果我们 : 47
#这种观点 : 46
#所有这些 : 44
#这个世界 : 40
#他们自己 : 38
#我们可以 : 37

#比较主流的其它同学的输出结果:其中的几个二元词组多1-2两个频数

version_1存在的问题：
错误1：我单纯用空格split的时候，如果出现“因为  他们”（中间有两个空格）,就会出现[’因为‘,’‘,’他们‘]中间的空元素。这个时候如果用
if len(wordlist[i]) >= 6 and len(wordlist[i+1]) >= 6
这个语句的时候，就会把这个二院词组给错过，所以会少统计。于是我又改了version_2, 为了防止双空格的出现，我觉得有必要把所有空格都去除掉

### [version_2](https://github.com/CarolLei/MachineLearning/blob/master/exercise0_v2.py)
a) 用re进行pattern的设置，用findall代替
b) 用codecs加了encoding = utf-8的选项，由\x改成了\u的输出，且直接print .read()后的问件会直接看到中文
c) pattern中添加了u’\u在前面，而不是r’\u，且使用了[\u4e00-\u9fa5]+]的条件

version_2存在的问题：
错误2：我上面的version_1避免了一个问题，即如果说源文件data.txt里面的标点符号不是左右都有空格的话，split以后就会出现这种情况：“因为， 他们”会变成「因为, 他们」,当然这样就会形成一个新的二元词组，是“因为，他们”，它不可能被统计进入「因为 他们」 这个二元词组。
不过事实上，跨越标点符号的这种类型的词组本来就不应该被统计，但是我在修改成version_2以后，用findall语句的时候，”因为 , 他们” 会被我处理成「因为 他们」而计入统计，其结果是频数又过多，果不其然，我的输出结果，不但数量增多，而且连二元词组都换了几个:
#输出结果
#这种情况 : 77
#没有什么 : 70
#这个问题 : 57
#因为他们 : 55
#如果我们 : 50
#所有这些 : 47
#这种观点 : 46
#这个世界 : 40
#但是如果 : 38
#他们自己 : 38
#可以很明显的看到，“但是，如果”这种二元词组的增多，还有”如果，我们”这样的二院词组增多，就是由于这个原因(我猜测)

## **遇到的难题**
我的两个版本都从存在问题，就是关于上述问题的解决始终让我比较困扰，还在思考用jieba来解决
总结一下，就是version_1存在错误1，version_2存在错误2，这还只是我想到的确实会出现的问题，可能还有很多我就没有觉察出的问题

## **新学到的东西**
a) 字典的sort方法和lambda函数
b) 代替使用sort方法的Counter容器, 以及其所在的Collections模块
c) 正则化模块re的用法,其中含有findall,match,search等函数
d) re中pattern的各种设置方法，还有r’\u...和u’\u...的区别
e) codecs函数的使用，对于编码变为unicode的理解,包括不同版本的操作系统，mac和windows下不同的编码格式

## **待继续理解的东西**
a) 继续理解编码，辅助codecs还有re模块，对于gbk和unicode还是觉得很混乱，包括encoding和的decoding命令
b) 正则化的pattern条件还需要用的更熟练，不太懂u‘和r’的区别，知道r是raw，u应该是unicode，但是整个mac的编译环境又是unicode？
c) 还有很多同学的代码没有看懂，对于如何优化以节省空间或者时间没有头绪
还应该继续多看看同学们的实现代码
d) \x和\u的len()是不同的，一个是3一个是1，原因为何，我也只是反复print实践出来的
e) jieba module还不清楚具体的使用方式，看到很多同学都用了这个进行重新的分词操作，因为原文件确实存在空格过多的问题
f) 我看到有同学直接用url读取的txt文件，待学习，我是直接下载下来的笨办法

## **本人基础以及对课程的一些期待**
我本科是统计背景，偏文商科，对于传统的统计方法和计量内容都有过系统的学习。我曾经在Coursera上以98%的成绩完成了Andrew Ng 在 Stanford 开设的 Machine Learning 课程，觉得有很大的收获，其中的作业我是用Octave完成的。那个课程以定性的练习为主，每个章节后面的编程内容都有很多的提示，所以处理起来不太难。
特别认同阳老师提出的[元认知]概念，在做这个作业的过程中发现自己效率低下,经常会觉得思绪很混乱,解决问题就像使用一个不断向上递归的函数，反复翻到上层去查找相关知识，可以说比较痛苦。苦于自己的编程基础和计算机知识，又缺乏编程实践的环境，总觉得缺乏一种关于学习的学习方法。深感自己在编程上面不太开窍。唯一值得欣慰的是，作为学生还有较充裕的时间。再说说期待吧：

a) 希望这门课能够授人以渔，不管是编程方面的(尤其希望自己能在这方面有所突破)，还是机器学习本身的知识方面的。
b) 希望能多推荐一些自学的链接，在整个课程中能突破阅读英文一手资料的心理障碍(感觉英语水平够了，但是一直没有这个习惯)
c) 希望能有很宏观的架构地图，包括NLP的发展路径，如果能推荐一些经典文献阅读学习就再好不过了
d) 将来自己是有意向从事这方面的一个研究，可能跨学科这样，所以希望能从这门课中更进一步了解自己的兴趣和能力

**Comment by ouyangzhiping** [comment]
很棒的思考。

第一个问题是开智特色，哈哈。童牧老师的文章同样可以参考：[M. Tong 的评论 (7)](https://www.douban.com/people/demon386/reviews)  

第二个问题、第三个问题可以参考这里：[[尉阮杰] 完成 DL101 入学挑战啦 · Issue #2 · OpenMindClub/DeepLearningStartUp](https://github.com/OpenMindClub/DeepLearningStartUp/issues/2)

**Comment by CarolLei** [comment]
感谢阳老师的资源分享！

**Comment by Jhangsy** [comment]
思考的很多，总结的很好~
