### ISSUE TITLE
标点符号前后的词语是否算「二元词组」？

### ISSUE THREAD

**Issue by iewaij** [OpenMindClub/DeepLearningStartUp#4]
当文章出现如下这句话时：「1. 今天天气很好，可是地球毁灭了。2. 我很忧心。」

「很好 可是」、「了 我」可以当作「二元词组」吗？

**Comment by CrickeySong** [comment]
@iewaij 可以哈，以分词结果为准。虽然这个例子里面这样切确实不太『合理』，但是只要量不是太多，影响不大。
