### ISSUE TITLE
[gaofqmt]完成DL101入学挑战！

### ISSUE THREAD

**Issue by gaofqmt** [OpenMindClub/DeepLearningStartUp#41]
- [入学挑战仓库地址](https://github.com/gaofqmt/DLstartup.git)

- 重要的不是你有多么努力，重要的是作为一个独立的个体能够提供的究竟是什么。

- 但是深感自己在面对交付时的无能为力，要以此课程为起点提高自己的交付能力。

- 很期待在开智的第一门课程

**Comment by hscspring** [comment]
Hello, 看了下你的结果取得是 二字 词组，建议可以把结果放上来。  
看代码来说，有两个地方有点小问题，主要是 `while i <= len(content) - 3`，因为你后面有 i + 3，所以智力如果 -3 的话会超出范围，应该 -4；另外，i <= 2 那一段其实没起作用。

**Comment by gaofqmt** [comment]
运行结果：
这种 情况 77 

没有 什么 70 

这个 问题 57 

因为 他们 55 

如果 我们 50 

所有 这些 47 

这种 观点 46 

这个 世界 40 

他们 自己 38 

我们 可以 37 

Hi, 感谢指正，是的。i <= 2那部分是多余的，需要把i ＝ 2 和 i ＝ len(conten) - 3 单独验证一下，不然引用会超出范围。

**Comment by gaofqmt** [comment]
很遗憾，还没有收到通知可以参加课程的邮件。
按照任务完成的情况，大概是不能收到了。
很希望能够参加，所以能不能破一下例呢。
相信这个课程能够让我受益良多。
期望您的回复！

祝一切顺利！

**Comment by sunnyhuang42** [comment]
谢谢 @gaofqmt 对开智的认可和支持，建议先增强相关基础，三个月后参加下一期，受益会更大哦：）

也可以先参加开智学堂的 Python 基础班（6 月前后）或数据科学基础班（4 月中下旬），这两门课相对现在这门深度学习入门课难度较低，更容易上手。

**Comment by gaofqmt** [comment]
我知道自己基础还比较差，也感谢开智能为学员的付出负责。
但是不论跟的有多么困难，我也想要去跟一下。谢谢考虑。

**Comment by gaofqmt** [comment]
首先
自己基础较差，思考不充分，也没能参考其他同学的代码，导致没能按时完成任务。
但是不管怎样还是希望把任务完成。
开始由于比较着急，所以具体看过哪位同学的代码不能一一列出来了，感谢他们。
最后是参考这个[方法](http://www.katrinerk.com/courses/python-worksheets/language-models-in-python)，修改了代码。
运行结果如下：
的人 : 923
他的 : 503
自己的 : 480
上的 : 356
他们的 : 335
人的 : 293
的时候 : 261
就会 : 225
的东西 : 207
都是 : 206

祝 一切顺利！

**Comment by gaofqmt** [comment]
重新修改了一下任务2的[代码](https://github.com/gaofqmt/DLstartup.git)
结果如下：
的人 : 923
他的 : 503
自己的 : 480
上的 : 356
他们的 : 335
人的 : 293
的时候 : 261
就会 : 225
的东西 : 207
都是 : 206

可以重新考虑一下我的上课资格吗？
祝 一切顺利！

**Comment by gaofqmt** [comment]
好吧，那就下次吧。
下次遇到时要从容些。

**Comment by sunnyhuang42** [comment]
嗯嗯很佩服 @gaofqmt 的坚持，但 2500 CNY 毕竟不是小数目。还是建议补足基础后下期再来，现在过来很容易给开智捐学费，这笔钱开智收得不踏实。且下期课程经过这期的迭代，也会更完善哦：）
