### ISSUE TITLE
洋葱头完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by Zwiebeln** [OpenMindClub/DeepLearningStartUp#42]
仓库地址：
https://github.com/Zwiebeln/Python-bungen

输出：
> ➜  lpthw  python dualWordList.py
>  这种 情况: 77
>  没有 什么: 70
>  这个 问题: 57
>  因为 他们: 55
>  如果 我们: 50
>  所有 这些: 47
>  这种 观点: 46
>  这个 世界: 40
>  他们 自己: 38
>  我们 可以: 37

感想：
之前几周还在十分怠惰地复习期末，22号考完试当晚就开始精神抖擞地抓起本子学python。自己选择的事+截止日期果然是拖延癌晚期的万灵药。
解析题目：
原文里词语乍看是被分好了，但还是有一些分词和我作为人类第一反应的切割方式不同，比如”一张 张“，”多种形式“， ”不敢肯定“。 不过我现在也还不了解自然语言，不知道这是不是那个圈子的行规。对这个问题我的下一步计划是：
1. 上网了解一下自然语言。
2. 看看别的同学对此的想法和他们的解决方案。
3. 查看其它中文分词方式，如 jieba（https://github.com/fxsjy/jieba） THULAC（http://thulac.thunlp.org）。
3. 改进代码。

对于Python：
第一次接触Python，相比于Java，确实抽象层级更高，简化了很多语法。比如省略分号，以及用缩进取代{}。由于时间有限，教程目前只完成了第17个，东一区27号零点之前要做完前42个。

最后说一个新年愿望：愿世界不再有时差之分，愿你们的deadline，也是我的deadline。

**Comment by Jhangsy** [comment]
愿世界没有 Deadline ！
