### ISSUE TITLE
柳白猿 完成入学挑战啦

### ISSUE THREAD

**Issue by xbaiyuan** [OpenMindClub/DeepLearningStartUp#44]
[代码地址](https://github.com/xbaiyuan/DeepLearningStartUp)
![](http://oenyn0bhf.bkt.clouddn.com/deepmind_initial_testScreen%20Shot%200029-02-24%20at%209.47.42.png)
感想：
因为之前有上过数据科学班和Python基础班。LPTHW的代码就不重复提交了。
Python课错过后等了整整一年，这门课也等了半年才等到。所以即便收到暖暖的建议——最好先专注Python、减少认知负荷——还是毅然想要上这门课。
一来是之前查了童牧晨玄的资料，感觉是位特别有趣的先生。
二来课程中的各位同学，很多都是熟面孔了，既然大家都是从同一起点开始，我就不能再拿「少壮不努力」来当借口，逃避每一次挑战。
三来发现了很多「大腿」，光是看他们的代码，揣摩其中思路，就让我受益非浅。

这门课我可能很难像其他同学一样徒手撸代码，但我给自己的最低要求是完成每周作业并且理解每一行代码的意思。那就开始吧。

**Comment by Jhangsy** [comment]
童老师确实是一个很有趣的人~

**Comment by newjueqi** [comment]
记得童牧晨玄还是国内推广影像阅读法的第一人，以前听了他的影像阅读法音频后还写了篇文章分享影像阅读法，然后真的有个阿姨看了这篇文章后问我影像阅读法相关的事情。后来自己用实践证明影像阅读法是无效，偶尔看到童牧晨玄一篇文章，说他也放弃了影像阅读法。

**Comment by xbaiyuan** [comment]
@Jhangsy 我们又见面了哈哈哈

@newjueqi 世间缘分不可思议啊，想起来我也是四年前看到阳老师文章，居然一路追到现在...印象中童老师是位敢尝试有趣的学习方法，有自己的知识体系，但也会不断改进自身理论的努力家。期待ing。

**Comment by Wangjunyu** [comment]
@xbaiyuan 随处可见，哈哈，共勉之

**Comment by xbaiyuan** [comment]
@Wangjunyu 又可以一起加油啦junyu兄！！！！
