### ISSUE TITLE
 JIANG09完成DL101入学挑战啦

### ISSUE THREAD

**Issue by JIANG09** [OpenMindClub/DeepLearningStartUp#45]
仓库地址：
1.Python前42个练习：https://github.com/JIANG09/Learn-Python-the-Hard-Way.git
2.计算二元词组频率：https://github.com/JIANG09/Deep-Learning-challenge-2.git

感想：
感想实在很多。作为毫无编程经验的文科小白，啃了LPTHW前40个练习。感觉这40个练习并不是很难，还是可以理解运用。
看第二题的第一眼就很懵，从开始懵到现在。于是发了一个issue希望的得到解答。后来实在等不急了，就看了各位同学的作业，然后找了几份感觉比较简洁能大概读懂的代码，一行一行的死磕，看不懂的函数或者符号就上网查，同时Python练习也在跟进，这样看下来，大概是懂了大半，虽然一些细节上还是不是很懂。
思路大概清楚了：先除去标点，再用split（）把文章分成一个词组的列表，然后组成“w1+空格+w2” 的形式组成二元词组，最后用Counter里面的most_common（）算出频率最高的前10。于是磕磕绊绊终于写完，但是在输出的时候是中文乱码，又仔细上网查了为什么是中文乱码以及怎么解决，但是结果还是没能正确输出中文（会继续弄清这个问题）。
结果不是尽如人意，和小伙伴们的差距也很大，作业做得吃力，但是平心而论自己也尽力了。4天之内搞定了Python的前40个练习，这一点还比较欣慰。但是后一个作业吃力，是因为之前从来没接触过。感觉这门课将会是一个巨大挑战。但是自己一直有个巨大的心愿就是do something cool, 自己感觉要补的很多，但是一定会尽力而为。
最后想请教一直在考虑的问题：1.之前没有上过开智的其他课程，需要其他课程作为基础吗？还是尝试直接上这个课程？
2.如果不适合这个课程，那有没有应该作为基础学习的书或者课程？我可以先自学或者参加其他课程，先做准备。
3.github 和git都用的不熟练，有没有推荐的运用指南？

**Comment by Jhangsy** [comment]
>1.之前没有上过开智的其他课程，需要其他课程作为基础吗？还是尝试直接上这个课程？

如果可以完成入学任务是可以直接上的，不过肯定会比遇到很多困难。因为童老师并不是手把手的交给你编程，而是提供一个大概思路，不过独立完成是很有收获的~

>如果不适合这个课程，那有没有应该作为基础学习的书或者课程？我可以先自学或者参加其他课程，先做准备。

基础的课程还有 __Python 基础班__ 和 __数据科学基础班__ 难度要低一点，对新手比较友好~

> github 和git都用的不熟练，有没有推荐的运用指南

参见官方文档或者 [Git教程 - 廖雪峰的官方网站](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)
