### ISSUE TITLE
代码上传GitHub遇到的问题

### ISSUE THREAD

**Issue by kksmart** [OpenMindClub/DeepLearningStartUp#47]
各位同学，本人上传代码到GitHub的时候需要配置SSH Keys,目前遇到了这样一个问题：
在终端输入：ssh -T git@github.com
显示的是：ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
stackoverflow的解决方案是修改DNS：将192.169.16.1 修改成8.8.8.8和8.8.4.4
我着该方法去执行，还是没有效果，希望那位同学帮忙解答下这个问题。多谢！

**Comment by scottming** [comment]
没那么复杂吧，直接参考github官方不就好了
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

另外提问，说明一下自己的操作系统，终端环境等，比较好。

**Comment by kksmart** [comment]
好的，多谢！我先试试

**Comment by kksmart** [comment]
好的，多谢，我先试试
