### ISSUE TITLE
nddd完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by nddd** [OpenMindClub/DeepLearningStartUp#49]
第一题：

练习1：第一个程序

In [1]:

print "Hello World!"
print "Hello Again!"
print "I like typing like this."
print "This is fun."
print "Yay! printing."
print "I'd much rather you 'not'."
print 'I "said" do not much this'

Hello World!
Hello Again!
I like typing like this.
This is fun.
Yay! printing.
I'd much rather you 'not'.
I "said" do not much this

练习2：注释和井号

In [2]:

# A comment,this is so you can reach your program later.
# Anything after the # is ignored by python.

print "I could have code like this." # and the comment after is ignored
# You can also use a comment to "disable" or comment out a piece of code :
# print "This won't run."
print "This will run."

I could have code like this.
This will run.

练习3：数字和数学计算

In [3]:

print "I will now count my chickens:"
# 打印小鸡计算的结果
print "Hens:", 25 + 30 / float(6)
# 打印公鸡计算的结果
print "Rooster", 100 - 25 * 3 % 4
print "Now I will count the eggs:"
# 打印计算鸡蛋结果,已转换成浮点数
print 3 + 2 + 1 - 5 + 4 % 2 - 1 / float(4) + 6
print "Is it true that 3 + 2 < 5 - 7" 
# 打印3 + 2 < 5 - 7的计算结果
print 3 + 2 < 5 - 7
print "What is 3 + 2 ?", 3 + 2
print "What is 5 - 7 ?", 5 - 7
print "Oh that's why it's False."
print "How about some more."
print "Is it greater ?", 5 > -2
print "Is it greater or equal ?", 5 >= -2
print "Is it less or equal ?", 5 <= -2

I will now count my chickens:
Hens: 30.0
Rooster 97
Now I will count the eggs:
6.75
Is it true that 3 + 2 < 5 - 7
False
What is 3 + 2 ? 5
What is 5 - 7 ? -2
Oh that's why it's False.
How about some more.
Is it greater ? True
Is it greater or equal ? True
Is it less or equal ? False

练习4：变量和命名

In [4]:

cars = 100
space_in_a_car = 4.0
drivers = 30
passengers = 90
cars_not_driver = cars - drivers
cars_driven = drivers
carpool_capacity = cars_driven * space_in_a_car
average_passengers_per_car = passengers / cars_driven

print "There are ", cars, "cars available."
print "There are only ", drivers, "drivers available."
print "There will be ", cars_not_driver, "empty cars today."
print "We can transport ",carpool_capacity, "people today."
print "We have ", passengers, "to carpool today."
print "We need to put about ",average_passengers_per_car, "in each car."

There are  100 cars available.
There are only  30 drivers available.
There will be  70 empty cars today.
We can transport  120.0 people today.
We have  90 to carpool today.
We need to put about  3 in each car.

练习5：更多的变量和打印

In [5]:

my_name = 'Zed A. Shaw'
my_age = 35 # not a lie
my_height = 74 # inches
my_weight = 180 # lbs
my_eyes = 'Blue'
my_teeth = 'White'
my_hair = 'Brown'

# %s 字符串点位符
print "Let's talk about %s." % my_name
# %d 整数点位符
print "He's %d inches tall ." % my_height
print "He's %d pounds heavy." % my_weight
print "Actually that's not too heavy."
print "He's got %s eyes and %s hair." % (my_eyes, my_hair)
print "His teeth are usually %s depending on coffee." % my_teeth

# this line is tricky,try to get it exactly right.
print "If I add %d , %d, and %d I get %d." % (my_age, my_height, my_weight, my_age + my_height + my_weight)

Let's talk about Zed A. Shaw.
He's 74 inches tall .
He's 180 pounds heavy.
Actually that's not too heavy.
He's got Blue eyes and Brown hair.
His teeth are usually White depending on coffee.
If I add 35 , 74, and 180 I get 289.

练习6：字符串与文本

In [6]:

x = "There are %d types of people." % 10
binary = "binary"
do_not = "don't"
y = "Those who know %s and those who %s." % (binary, do_not)

print x
print y
# %r是将内容转换为字符串输出，%s是输出字符串内容
print "I said: %r." % x
print "I also said:'%s'." % y

hilarious = False
joke_evaluation = "Isn't that joken so funny ?! %r"

print joke_evaluation % hilarious

w = "This is the left side of ..."
e = "a string with a right side."
# + 字符串连接
print w + e

There are 10 types of people.
Those who know binary and those who don't.
I said: 'There are 10 types of people.'.
I also said:'Those who know binary and those who don't.'.
Isn't that joken so funny ?! False
This is the left side of ...a string with a right side.

练习7：更多打印

In [7]:

print "Mary had a little lamb."
print "Its fleece was white as %s." % 'snow'
print "And everywhere that Mary went."
print "." * 10 # what'd that do ?

end1 = "C"
end2 = "h"
end3 = "e"
end4 = "e"
end5 = "s"
end6 = "e"
end7 = "B"
end8 = "u"
end9 = "r"
end10 = "g"
end11 = "e"
end12 = "r"

# watch that comma at the end. try removing it to see what happens.
# 逗号在一行显示
print end1 + end2 + end3 + end4 + end5 + end6,
print end7 + end8 + end9 + end10 + end11 + end12

Mary had a little lamb.
Its fleece was white as snow.
And everywhere that Mary went.
..........
Cheese Burger

练习8：打印，打印

In [8]:

formatter = "%r %r %r %r"

print formatter % (1, 2, 3, 4)
print formatter % ("one", "two", "three", "four")
print formatter % (True, False, False, True)
print formatter % (formatter, formatter, formatter, formatter)
print formatter % (
    "I had this thins.",
    "That you could type up right.",
    "But it didn't sing.",
    "So I said goognight."
)

1 2 3 4
'one' 'two' 'three' 'four'
True False False True
'%r %r %r %r' '%r %r %r %r' '%r %r %r %r' '%r %r %r %r'
'I had this thins.' 'That you could type up right.' "But it didn't sing." 'So I said goognight.'

练习9：打印，打印，打印

In [9]:

# Here's some new strange stuff, remember type it exactly.

days = "Mon Tue Wed Thu Fri Sat Sun"
months = "Jan\nFeb\nMar\nApr\nMay\nJun\nJul\nAug"

print "Here are the days:", days
print "Here are the months:", months

print """
There's something going on here.
With the three double-quotes.
We'll be able to type as much as e like.
Even 4 lines if we want,or 5, or 6.
"""

Here are the days: Mon Tue Wed Thu Fri Sat Sun
Here are the months: Jan
Feb
Mar
Apr
May
Jun
Jul
Aug

There's something going on here.
With the three double-quotes.
We'll be able to type as much as e like.
Even 4 lines if we want,or 5, or 6.

练习10：那是什么？

In [10]:

tabby_cat = "\tI'm tabbed in."
persian_cat = "I'm split \non a line."
backslash_cat = "I'm \\ a \\ cat."
fat_cat = """
I'll do a list:
\t* Cat food
\t* Fishies
\t* Catnip\n\t* Grass
"""

print tabby_cat
print persian_cat
print backslash_cat
print fat_cat

	I'm tabbed in.
I'm split 
on a line.
I'm \ a \ cat.

I'll do a list:
	* Cat food
	* Fishies
	* Catnip
	* Grass

练习11：提问

In [11]:

print "How old are you ?",
age = raw_input()

print "How tall are you ?",
height = raw_input()

print "How much do you weight ?",
weight = raw_input()

print "So,you're %r old , %r tall and %r heavy." % (age, height, weight)

How old are you ?27
 How tall are you ?175
 How much do you weight ?126
 So,you're '27' old , '175' tall and '126' heavy.

练习12：提示别人

In [1]:

age = raw_input("How old are you ?")
height = raw_input("How tall are you ?")
weight = raw_input("How much do you weight ?")

print "So, you're %r old, %r tall and %r heavy ." % (age, height, weight)

How old are you ?35
How tall are you ?6'22"
How much do you weight ?180lbs
So, you're '35' old, '6\'22"' tall and '180lbs' heavy .

练习13：参数，解包，变量

In [1]:

from sys import argv

argv = ("ex13","first","second","third")

script, first, second, third = argv

print "The script is called:", script
print "Your first variable is:", first
print "Your second variable is:", second
print "Your third variable is:", third

The script is called: ex13
Your first variable is: first
Your second variable is: second
Your third variable is: third

练习14：提示和传递

In [2]:

from sys import argv

argv = ("ex13","张三")

script, user_name = argv
prompt = '>'

print "Hi %s, I'm the %s script." % (user_name, script)
print "I'd like to ask you a few questions."
print "Do you like me %s ?" % user_name
likes = raw_input(prompt)

print "Where do you live %s?" % user_name
lives = raw_input(prompt)

print "What kind of computer do you have?"
computer = raw_input(prompt)

print """
Alright, so you said %r about liking me.
You live in %r. Not sure where that is.
And you have a %r computer. Nice.
""" % (likes, lives, computer)

Hi 张三, I'm the ex13 script.
I'd like to ask you a few questions.
Do you like me 张三 ?
>Yes
Where do you live 张三?
>JiNan
What kind of computer do you have?
>Mac

Alright, so you said 'Yes' about liking me.
You live in 'JiNan'. Not sure where that is.
And you have a 'Mac' computer. Nice.

练习15：读取文件

In [9]:

file_name = "./ex15_sample.txt"
txt = open(file_name)

print "Here's your file %r: " % file_name
print txt.read()
txt.close()

print "Type the filename again:"
file_again = raw_input(">")
txt_again = open(file_again)
print txt_again.read()
txt_again.close()

Here's your file './ex15_sample.txt': 
This is stuff I typed into a file. 
It is really cool stuff. 
Lots and lots of fun to have in here.
Type the filename again:
>ex15_sample.txt
This is stuff I typed into a file. 
It is really cool stuff. 
Lots and lots of fun to have in here.

练习16：读写文件

In [10]:

filename = "ex15_sample.txt"

print "We're going to erase %r." % filename
print "If you don't want that,hit CTRL-C(^C)."
print "If you do want that, hit RETURN."

raw_input("?")

print "Opening the file ..."
target = open(filename, 'w')

print "Truncating the file.Goodbye!"
target.truncate()

print "Now I'm going to ask you for three lines."

line1 = raw_input("line 1 : ")
line2 = raw_input("line 2 : ")
line3 = raw_input("line 3 : ")

print "I'm going to write these to the file."

target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")

print "And finally, we close it ."
target.close()

We're going to erase 'ex15_sample.txt'.
If you don't want that,hit CTRL-C(^C).
If you do want that, hit RETURN.
?I'm line1.
Opening the file ...
Truncating the file.Goodbye!
Now I'm going to ask you for three lines.
line 1 : I'm line1
line 2 : I'm line2
line 3 : I'm line3
I'm going to write these to the file.
And finally, we close it .

练习17：更多的文件操作

In [1]:

from sys import argv 
from os.path import exists

from_file = "ex15_sample.txt"
to_file = "copied.txt"

print "Copying from %s to %s " % (from_file, to_file)
# we could do these two on one line too, how?
input = open(from_file)
indata = input.read()

print "Does the output file exists ? %r " % exists(to_file)

print "Ready, hit RETURN to continue,CTRL-C to abort."
raw_input()

output = open(to_file, 'w')
output.write(indata)

print "Alright, all done."

output.close()
input.close()

Copying from ex15_sample.txt to copied.txt 
Does the output file exists ? False 
Ready, hit RETURN to continue,CTRL-C to abort.

Alright, all done.

第二题：
from  collections  import Counter
import codecs
# load file
f = codecs.open("happiness_seg.txt","r",encoding='utf-8')
wordList = f.read().split(" ")
# genneration dict
c = Counter()
# word count
for i in range(0,(len(wordList) - 1)) :
    if len(wordList[i]) >= 2 and len(wordList[i + 1]) >= 2:
        double_words = wordList[i] + wordList[i + 1]
        c[double_words] = c[double_words] + 1

most_words = c.most_common(10)
for i in range(len(most_words)):
    print most_words[i][0],most_words[i][1]

输出：

这种情况 77
没有什么 70
这个问题 56
因为他们 54
如果我们 47
这种观点 46
所有这些 44
这个世界 40
他们自己 38
我们可以 37

**Comment by CrickeySong** [comment]
@nddd 你还没有填写个人基础评估表，请尽快微信联系 一休（aiopenmind）哦
