### ISSUE TITLE
鐡屋完成 DL101 入学挑战啦！ 

### ISSUE THREAD

**Issue by iewaij** [OpenMindClub/DeepLearningStartUp#5]
## 完成说明
1. 代码已上传在[我的仓库](https://github.com/iewaij/deep-learning-lab)里。
2. 因为 Learning Python the Hard Way 去年就完整地做过一遍，所以没有放上。
3. 我的输出结果如下：
```
词组：「的 人」 频率：930
词组：「他 的」 频率：503
词组：「自己 的」 频率：480
词组：「上 的」 频率：356
词组：「他们 的」 频率：335
词组：「人 的」 频率：293
词组：「的 时候」 频率：261
词组：「就 会」 频率：225
词组：「的 东西」 频率：207
词组：「都 是」 频率：206
[Finished in 0.3s]
```

## 心得
1. 用时大概2~3小时，比我预想的短很多（我本以为要用到 jieba 分词），而且写代码时进入「心流」后时间过得极快。
2. 用了 `with open("happiness_seg.txt", "rt") as textfile:` 来打开文件，这样不必再次关闭文件。
3. 因为文本本身已经用空格分好词，所以我先用 `replace()` 去除标点符号再使用 `split()` 将文本转换成列表，还有其他方法，例如使用 `translate()`，但 `replace()` 的速度更快。
4. 用了 for 循环和 `append()` 来组合「二元词组」，本来想用递归函数，但似乎 Python 对递归函数的支持非常弱。
5. 统计词频参考了 [Python3-cookbook 1.12 序列中出现次数最多的元素](http://python3-cookbook.readthedocs.io/zh_CN/latest/c01/p12_determine_most_freqently_items_in_seq.html)，比起使用字典按照 value 排序的方法提升了很多效率。

## 问题
1. 写了一个组合「二元词组」的递归函数，但对于元素个数1000以内列表可用，更长的列表不行。我瞎猜测是因为 Python 对递归函数的支持太弱。
```Python
output_list = []
def combine_short (input):
	# a recursive function but only workable when input list is not too long
	global output_list
	if len(input) <= 1:
		pass
	else:
		output_list.append(input[0] + input[1])
		combine_short(input[1:])
```

**Comment by txytju** [comment]
代码写的很棒！期待你在课程中的精彩表现！
