### ISSUE TITLE
gunuo完成入学挑战

### ISSUE THREAD

**Issue by gunuo** [OpenMindClub/DeepLearningStartUp#51]
忘了说，笨办法学python我前面20个练习做了，因为都太小了，就直接在jupyter notebook里做的，没有一个一个保存。

[代码地址](https://github.com/gunuo/DeepLearning/blob/master/enrollmenttask.py)

## 思路和挑战
- 最终思路是这样的，因为分词分的不好，所以先把原文重新合并，然后用常用的句子间隔符号来切分句子。接着再用jieba分词来分词。分完词后再计算二元词语。
但是还是没有解决文章重复的问题。而且我也没整成nltk。还是用的pandas库。
- 中间遇到的几次挑战
   1. 系统问题。包括公司windows系统装不了jieba和nltk，下载了python3.6又发现jupyter notebook怎么也调用不了python3.6。又返回来用python2。本来是想规避字符串encoding的问题，怕出错，结果还是规避不了。这个折腾了好长时间。
   2. 原始文件开始下载有问题。我用url替代。结果nltk语句中的raw识别出来的字符少的可怜。估计是py2的文本变换的语句不熟悉导致。
    3. 对nltk库不熟悉。jieba分词的时候，type出来的居然不是string。find语句出来是-1，表明返回错误。因为时间太紧，不知道是哪里出的问题，最后决定还是使用pandas库里的DataFrame。合并和计数这两个功能算是有以前的程序。所以找了找，感觉好多了。
   4. 分词的程序之前写的不对。快到时间了，别人好心给我修改了，不然怎么也提交不了了。

很惭愧，完成的晚了。

**Comment by gunuo** [comment]
早上看到有同学回复没有收到课程通知，我也没收到，心下有些惶惶，还是希望能参加学习。因为我有意通过这个课程完成一些积蓄在内心很久的想法。

债券交易和股票交易不同，股票交易多数是结构化数据，一般只需要价/量信息，修正好的财务数据和分析师预期，就可以对策略有所建树。债券交易则不同。首先使用财务数据是过去的信息，价格交易不连续，成交数量不透明，如果用时间序列的方式来看，缺失点太多造成方差太大，定价的区间显著增加。大部分时期，信用债交易在中观层次都是缺失的。要么是活跃券交易，有报价的品种和没有报价的品种价格差异巨大。要么是形式上的综合分析，只根据变动较小的群体去估测整个集合的价值走向。交易所根据贝叶斯推断的估值方法和银行间通过活跃券定价的方法也存在巨大差异。

我想通过这次学习，看能不能有更好的武器来进行中观层次的分析。目前网页读取负面信息和重要信息对债券交易贡献不大，因为信用利差变动是临界值变动，大多数时候，负面信息并不会带来利差的变动。信息本身定价的权重难以衡量。

**Comment by Jhangsy** [comment]
可以请你提交一下程序运行结果给我们看看么？

**Comment by gunuo** [comment]
out：
这种情况    77
没有什么    70
这个问题    57
因为他们    55
如果我们    50
所有这些    47
这种观点    46
这个世界    40
他们自己    38
我们可以    37
一个孩子    36
我们必须    34
这种情形    32
如果一个    31
他们认为    31
但是如果    31
这种态度    29
现代世界    28
认为自己    28
任何一个    27
我们不能    26
心理分析    25
......
