### ISSUE TITLE
garra完成 DL102 入学任务啦

### ISSUE THREAD

**Issue by garra0123** [OpenMindClub/DeepLearningStartUp#67]
### 基础任务1 
参考jieba中extract_tags方法

### 进阶任务1  
使用sympy中diff方法求导

**Comment by ruibofeng** [comment]
@garra0123 ，你的代码运行过吗？最好把结果贴出来，我看你用的大概是python3.X，你的代码里有个变量命名为`bytes`，这个是keyword，应该不能作为变量名。

---
刚刚试了一下，貌似也可以运行，太诡异了，但不建议这样的命名方法。

**Comment by garra0123** [comment]
谢谢指点~~

# 运行结果
基础任务一

![image](https://user-images.githubusercontent.com/24825832/31336437-72ed1a06-acbc-11e7-8f1c-80f239ea837a.png)
进阶任务一
![image](https://user-images.githubusercontent.com/24825832/31336499-ae48efa8-acbc-11e7-90e3-e375bc0ecd46.png)
