### ISSUE TITLE
[赵玉勇]完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by chozee** [OpenMindClub/DeepLearningStartUp#7]
##### 1. 含有你上述挑战成果的 GitHub 仓库地址
> https://github.com/chozee/DeepLearning-yuyongzhao.git
其中tuple_count.py是统计元组字数的脚本，附带word原始输入文件；其余的*.py为练习的脚本。

##### 2. 感想
> 1. 编程跟理论学习不同，主要是要实践，你以为你明白的东西不经过实践检验没办法做到真正的明白。你总会遇到各种各样的问题，在解决各种各样问题过程中，渐渐的会加深你对所学的东西的理解。学习编程切忌眼高手低，你的大脑告诉你你懂了，其实如果不经过你的手去证实的话，很可能你的大脑欺骗了你，所以编程这门学科，切忌一定要用手证明而不要听你大脑告诉你的。
> 2. 对于NLP最想关注的未来的发展趋势、应用场景、比较成熟的应用、存在的问题、学习NLP的一般路径、国内外的一些专业公司情况、以及NLP在人工智能和机器学习中所处的位置。我个人对人工智能和机器学习特别感兴趣，希望下一个公司能做相关的工作并且深耕几年。
> 3. Deep Learning是一种学习方法？那么在学习NLP和其他领域有什么优势？

##### 3. 【二元词组】结果
> [这种_情况] = [77]
[没有_什么] = [70]
[这个_问题] = [57]
[因为_他们] = [55]
[如果_我们] = [50]
[所有_这些] = [47]
[这种_观点] = [46]
[这个_世界] = [40]
[他们_自己] = [38]
[我们_可以] = [37]

**Comment by Jhangsy** [comment]
注意是统计 **二元词组**，而不是统计词语哟·~ 看看同学们的结果再修改一下吧！

**Comment by chozee** [comment]
@Jhangsy  已更正，多谢指正！！！
