### ISSUE TITLE
[郝文飞]完成 DL101 入学挑战啦

### ISSUE THREAD

**Issue by tjuhwf** [OpenMindClub/DeepLearningStartUp#9]
# 完成说明
**1.** [代码地址](https://github.com/tjuhwf/Deeplearn)

**2.**我的输出结果：

这种 情况 : 77
没有 什么 : 70
这个 问题 : 57
因为 他们 : 55
如果 我们 : 50
所有 这些 : 47
这种 观点 : 46
这个 世界 : 40
他们 自己 : 38
我们 可以 : 37

# 感想
**1.**统计出现频率最高的二元词组，采用的是字典排序；[1.12 序列中出现次数最多的元素](http://python3-cookbook.readthedocs.io/zh_CN/latest/c01/p12_determine_most_freqently_items_in_seq.html)这个算法实现的话效率会更高；完成任务的时候我没有想到这种方法，代码中贴的是自己想到的方法
**2.**想在机器学习方面学习一下，怕跟不上社会呀，好期待开智的课程呀

**Comment by txytju** [comment]
貌似郝同学和两位教练是校友呢~
