### ISSUE TITLE
Strong-Q完成 DL102 入学任务啦

### ISSUE THREAD

**Issue by Strong-Q** [OpenMindClub/DeepLearningStartUp#93]
## 编译环境
* Windows IDLE Python 3

## 基础任务
* [代码地址](https://github.com/Strong-Q/DeepLearningStartUp/blob/master/DL102.py)

## 输出结果
>[('的 人', 921), ('他 的', 503), ('自己 的', 479), ('上 的', 355), ('他们 的', 334), ('― ―', 329), ('人 的', 293), ('的 时候', 261), ('就 会', 225), ('的 东西', 207)]

## 思路
参考之前同学代码，利用空格做分隔符将文档读取成词库，再利用标点数组过滤标点符号存放二元词库，最后利用Conter的内置函数统计出频次最高的组合。

## 体会
不熟悉python编译环境，不知道如何安装zhon.hanzi包，不清楚那些编译软件方便使用和调试。先后尝试过Mac+sublimeText2 Python 2.7和 Windows IDLE Python 3.7。最后在Windows上运行成功。

**Comment by ruibofeng** [comment]
- 安装zhon包最简单的方法是用pip，具体内容可查阅zhon的文档

- 如果python不熟悉的话最好这段时间花时间好好学习一下，把《learn python the hard way》前半部分代码敲一遍。开发环境建议在mac下搭建，不建议用IDLE，试试命令行工具或者ipython notebook。
